<?php

use App\Models\Category;
use App\Models\MediaItem;
use App\Models\Page;
use App\Models\PortfolioProject;
use App\Models\Post;
use App\Models\SeoEntry;
use App\Models\SiteSetting;
use App\Models\User;

return [
    'resources' => [
        'users' => [
            'title' => 'Users',
            'description' => 'Manage admin accounts, content editors, roles and access.',
            'model' => User::class,
            'primary' => 'Add User',
            'search' => ['name', 'email', 'role', 'status'],
            'columns' => ['name' => 'Name', 'email' => 'Email', 'role' => 'Role', 'status' => 'Status'],
            'fields' => [
                ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => true],
                ['name' => 'password', 'label' => 'Password', 'type' => 'password', 'store_only' => false],
                ['name' => 'role', 'label' => 'Role', 'type' => 'select', 'options' => ['administrator', 'editor', 'seo-manager']],
                ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['active', 'invited', 'disabled']],
            ],
        ],
        'pages' => [
            'title' => 'Pages',
            'description' => 'Edit public website pages while keeping the same frontend URLs.',
            'model' => Page::class,
            'primary' => 'Create Page',
            'search' => ['title', 'slug', 'template', 'status'],
            'columns' => ['id' => 'ID', 'title' => 'Title', 'slug' => 'Slug', 'template' => 'Template', 'status' => 'Status'],
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'text', 'required' => true],
                ['name' => 'template', 'label' => 'Template', 'type' => 'select', 'options' => ['landing', 'content', 'services', 'technology', 'contact', 'legal', 'privacy-policy']],
                ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['published', 'draft', 'archived']],
                ['name' => 'excerpt', 'label' => 'Excerpt', 'type' => 'textarea'],
                ['name' => 'content', 'label' => 'Content', 'type' => 'textarea'],
                ['name' => 'meta_title', 'label' => 'Meta Title', 'type' => 'text'],
                ['name' => 'meta_description', 'label' => 'Meta Description', 'type' => 'textarea'],
            ],
        ],
        'posts' => [
            'title' => 'Posts',
            'description' => 'Create and manage blog content for the Laravel site.',
            'model' => Post::class,
            'primary' => 'New Post',
            'search' => ['title', 'slug', 'author', 'status'],
            'columns' => ['title' => 'Title', 'category.name' => 'Category', 'author' => 'Author', 'status' => 'Status'],
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'text', 'required' => true],
                ['name' => 'category_id', 'label' => 'Category', 'type' => 'category'],
                ['name' => 'author', 'label' => 'Author', 'type' => 'text'],
                ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['published', 'draft', 'archived']],
                ['name' => 'published_at', 'label' => 'Published At', 'type' => 'datetime-local'],
                ['name' => 'excerpt', 'label' => 'Excerpt', 'type' => 'textarea'],
                ['name' => 'content', 'label' => 'Content', 'type' => 'textarea'],
                ['name' => 'meta_title', 'label' => 'Meta Title', 'type' => 'text'],
                ['name' => 'meta_description', 'label' => 'Meta Description', 'type' => 'textarea'],
            ],
        ],
        'portfolio_projects' => [
            'title' => 'Portfolio',
            'description' => 'Manage featured portfolio projects and keep the frontend portfolio list dynamic.',
            'model' => PortfolioProject::class,
            'primary' => 'Add Portfolio Project',
            'search' => ['title', 'slug', 'category', 'status', 'tech_stack'],
            'columns' => ['title' => 'Title', 'category' => 'Category', 'featured' => 'Featured', 'status' => 'Status', 'sort_order' => 'Order'],
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'text', 'required' => true],
                ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
                ['name' => 'image', 'label' => 'Project Image', 'type' => 'file'],
                ['name' => 'excerpt', 'label' => 'Excerpt', 'type' => 'textarea'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
                ['name' => 'tech_stack', 'label' => 'Tech Stack', 'type' => 'text'],
                ['name' => 'url', 'label' => 'Project URL', 'type' => 'text'],
                ['name' => 'featured', 'label' => 'Featured', 'type' => 'select', 'options' => ['0', '1']],
                ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['published', 'draft', 'archived']],
                ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number'],
            ],
        ],
        'categories' => [
            'title' => 'Categories',
            'description' => 'Organize blog posts, services and content collections.',
            'model' => Category::class,
            'primary' => 'Add Category',
            'search' => ['name', 'slug', 'type'],
            'columns' => ['name' => 'Name', 'slug' => 'Slug', 'type' => 'Type', 'created_at' => 'Created'],
            'fields' => [
                ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true],
                ['name' => 'slug', 'label' => 'Slug', 'type' => 'text', 'required' => true],
                ['name' => 'type', 'label' => 'Type', 'type' => 'select', 'options' => ['blog', 'service', 'portfolio']],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ],
        ],
        'media' => [
            'title' => 'Media',
            'description' => 'Manage images and files used by the Laravel frontend.',
            'model' => MediaItem::class,
            'primary' => 'Add Media',
            'search' => ['title', 'path', 'type', 'status'],
            'columns' => ['title' => 'Title', 'path' => 'Path', 'type' => 'Type', 'status' => 'Status'],
            'fields' => [
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
                ['name' => 'path', 'label' => 'Path', 'type' => 'text', 'required' => true],
                ['name' => 'type', 'label' => 'Type', 'type' => 'select', 'options' => ['image', 'document', 'video']],
                ['name' => 'alt_text', 'label' => 'Alt Text', 'type' => 'text'],
                ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['active', 'draft', 'archived']],
            ],
        ],
        'seo' => [
            'title' => 'SEO',
            'description' => 'Control page titles, meta descriptions, redirects and indexing.',
            'model' => SeoEntry::class,
            'primary' => 'Add SEO Rule',
            'search' => ['url', 'title', 'indexing', 'status'],
            'columns' => ['url' => 'URL', 'title' => 'Title', 'indexing' => 'Indexing', 'status' => 'Status'],
            'fields' => [
                ['name' => 'url', 'label' => 'URL', 'type' => 'text', 'required' => true],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
                ['name' => 'indexing', 'label' => 'Indexing', 'type' => 'select', 'options' => ['index', 'noindex']],
                ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['good', 'needs-review', 'redirected']],
            ],
        ],
        'settings' => [
            'title' => 'Settings',
            'description' => 'Configure company details, site identity, contact channels and runtime options.',
            'model' => SiteSetting::class,
            'primary' => 'Add Setting',
            'search' => ['key', 'value', 'area', 'status'],
            'columns' => ['key' => 'Setting', 'value' => 'Value', 'area' => 'Area', 'status' => 'Status'],
            'fields' => [
                ['name' => 'key', 'label' => 'Setting Key', 'type' => 'text', 'required' => true],
                ['name' => 'value', 'label' => 'Value', 'type' => 'textarea'],
                ['name' => 'area', 'label' => 'Area', 'type' => 'select', 'options' => ['general', 'identity', 'contact', 'seo', 'system']],
                ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['active', 'disabled']],
            ],
        ],
        'leads' => [
            'title' => 'Leads & Inquiries',
            'description' => 'View and manage contact messages and quote requests from the frontend.',
            'model' => \App\Models\Lead::class,
            'primary' => 'Add Lead',
            'search' => ['name', 'email', 'company', 'type', 'status'],
            'columns' => ['name' => 'Name', 'email' => 'Email', 'type' => 'Type', 'status' => 'Status', 'created_at' => 'Date'],
            'fields' => [
                ['name' => 'type', 'label' => 'Type', 'type' => 'select', 'options' => ['contact', 'quote']],
                ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true],
                ['name' => 'email', 'label' => 'Email', 'type' => 'text', 'required' => true],
                ['name' => 'phone', 'label' => 'Phone', 'type' => 'text'],
                ['name' => 'company', 'label' => 'Company', 'type' => 'text'],
                ['name' => 'subject_or_service', 'label' => 'Subject / Service', 'type' => 'text'],
                ['name' => 'budget', 'label' => 'Budget', 'type' => 'text'],
                ['name' => 'timeline', 'label' => 'Timeline', 'type' => 'text'],
                ['name' => 'message', 'label' => 'Message', 'type' => 'textarea'],
                ['name' => 'document_path', 'label' => 'Attachment', 'type' => 'file'],
                ['name' => 'reference_page', 'label' => 'Reference Page', 'type' => 'url'],
                ['name' => 'contact_method', 'label' => 'Preferred Contact', 'type' => 'select', 'options' => ['email', 'phone']],
                ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['new', 'in-progress', 'closed']],
            ],
        ],
    ],
];
