<?php

return [
    'services' => [
        ['title' => 'E-Commerce Website Development', 'body' => 'Fast, secure online stores built for conversion across Shopify, WooCommerce, Magento and custom commerce stacks.'],
        ['title' => 'Custom Website & Web Application Development', 'body' => 'Scalable business websites, SaaS tools and portals tailored to your workflows instead of boxed templates.'],
        ['title' => 'Content Management Systems', 'body' => 'Easy-to-manage CMS platforms for pages, blog posts, images, SEO metadata and publishing workflows.'],
        ['title' => 'Blog & Content Website Design', 'body' => 'Performance-focused content experiences that keep articles readable, searchable and simple to maintain.'],
        ['title' => 'Mobile App Development', 'body' => 'Android and cross-platform apps with thoughtful UI, reliable performance and room to grow.'],
        ['title' => 'AI & Automation Solutions', 'body' => 'Chatbots, recommendations, predictive analytics and workflow automation for smarter operations.'],
        ['title' => 'UI/UX Design & Branding', 'body' => 'Clean product experiences, prototypes, visual identity and usability improvements.'],
        ['title' => 'Maintenance & Support', 'body' => 'Security monitoring, updates, bug fixes, backups and ongoing performance improvements.'],
        ['title' => 'Digital Strategy & Consulting', 'body' => 'Research, planning and technical guidance to help you choose the right digital direction.'],
    ],

    'technologies' => [
        'Laravel',
        'PHP',
        'Python',
        'JavaScript',
        'TypeScript',
        'React.js',
        'Vue.js',
        'Angular.js',
        'Node.js',
        'Express.js',
        'Next.js',
        'Nuxt.js',
        'Svelte',
        'jQuery',
        'HTML5',
        'CSS3',
        'Tailwind CSS',
        'Bootstrap',
        'SASS/SCSS',
        'MySQL',
        'PostgreSQL',
        'MongoDB',
        'Firebase',
        'Redis',
        'Elasticsearch',
        'Docker',
        'Kubernetes',
        'AWS',
        'Google Cloud',
        'Azure',
        'GitHub Actions',
        'CI/CD Pipelines',
        'Git',
        'REST APIs',
        'GraphQL',
        'WebSockets',
        'Java',
        'Spring Boot',
        'Kotlin',
        'C#',
        '.NET',
        'Go',
        'Rust',
        'Ruby',
        'Ruby on Rails',
        'Elixir',
        'Swift',
        'Objective-C',
        'Dart',
        'Flutter',
        'React Native',
        'Ionic',
        'Cordova',
        'WordPress',
        'Shopify',
        'Magento',
        'WooCommerce',
        'Drupal',
        'Joomla',
        'CodeIgniter',
        'Symfony',
        'Slim',
        'Yii',
        'CakePHP',
        'Django',
        'Flask',
        'FastAPI',
        'Strapi',
        'Sanity',
        'Contentful',
        'Strapi CMS',
        'Open Cart',
        'BigCommerce',
        'Adobe Experience Manager',
        'Figma',
        'Adobe XD',
        'Sketch',
        'Photoshop',
        'Illustrator',
        'Webpack',
        'Vite',
        'Babel',
        'ESLint',
        'Prettier',
        'Jest',
        'Vitest',
        'Mocha',
        'Cypress',
        'Selenium',
        'PHPUnit',
        'Pytest',
        'RSpec',
        'Jasmine',
        'Postman',
        'Insomnia',
        'Socket.io',
        'Pusher',
        'Stripe',
        'PayPal',
        'Razorpay',
        'Twilio',
        'SendGrid',
        'Mailchimp',
        'Auth0',
        'JWT',
        'OAuth2',
        'OpenAI',
        'TensorFlow',
        'PyTorch',
        'Scikit-learn',
        'Keras',
        'Hugging Face',
        'LangChain',
        'Llama',
        'Claude API',
        'GPT-4',
        'Computer Vision',
        'NLP',
        'Machine Learning',
        'Deep Learning',
        'AI/ML Automation',
        'Chatbots',
        'Predictive Analytics',
        'Godot',
        'GDScript',
        'Unity',
        'Unreal Engine',
        'Blender',
        'Three.js',
        'Babylon.js',
        'WebGL',
        'Canvas API',
        'SVG',
        'ffmpeg',
        'ImageMagick',
        'OpenCV',
        'Blockchain',
        'Ethereum',
        'Web3.js',
        'Solidity',
        'NFT Development',
        'Smart Contracts',
        'Metamask',
        'Crypto Payments',
        'Apache',
        'Nginx',
        'Caddy',
        'SSL/TLS',
        'Cloudflare',
        'Akamai',
        'CDN Services',
        'Load Balancing',
        'Caching Strategies',
        'API Rate Limiting',
        'Monitoring & Analytics',
        'Datadog',
        'New Relic',
        'Sentry',
        'LogRocket',
        'Google Analytics',
        'Mixpanel',
        'Segment',
        'SEO Tools',
        'Lighthouse',
        'Web Vitals',
        'Performance Optimization',
        'Accessibility (A11y)',
        'WCAG Compliance',
        'Progressive Web Apps',
        'Service Workers',
        'Offline-first Architecture',
        'GraphQL Federation',
        'API Gateway',
        'Message Queues',
        'RabbitMQ',
        'Kafka',
        'AWS SQS',
        'Event Sourcing',
        'CQRS',
        'Microservices Architecture',
        'Serverless',
        'AWS Lambda',
        'Google Cloud Functions',
        'Azure Functions',
        'Supabase',
        'Hasura',
        'Prisma',
        'TypeORM',
        'Sequelize',
        'Mongoose',
        'SQLAlchemy',
        'Hibernate',
        'Entity Framework',
        'Liquibase',
        'Flyway',
        'Database Migration',
        'Authentication',
        'Authorization',
        'Two-Factor Authentication',
        'Biometric Security',
        'Encryption',
        'Password Hashing',
        'API Security',
        'CORS',
        'CSRF Protection',
        'XSS Prevention',
        'SQL Injection Prevention',
        'OWASP Security',
        'Penetration Testing',
        'Security Audits',
    ],

    'projects' => [
        [
            'title' => 'Desi Run Rush',
            'category' => 'Game Landing Page',
            'image' => 'desi-run-rush.png',
            'body' => 'A high-energy landing page for a 3D endless runner with bold visuals, app-store CTA and gameplay storytelling.',
            'tech' => ['WordPress', 'SEO', 'Landing Page', 'Performance'],
            'url' => '/portfolio/',
        ],
        [
            'title' => 'WaBizFlow',
            'category' => 'SaaS Automation',
            'image' => 'wabizflow.png',
            'body' => 'A polished SaaS interface for CRM, WhatsApp messaging, invoicing, payments and business automation.',
            'tech' => ['Laravel', 'SaaS', 'CRM', 'Automation'],
            'url' => '/portfolio/',
        ],
        [
            'title' => 'Prime Breaks',
            'category' => 'Travel Platform',
            'image' => 'prime-breaks.png',
            'body' => 'A destination search website with strong hero imagery, booking intent and conversion-focused travel UX.',
            'tech' => ['WordPress', 'Travel UX', 'Search', 'Responsive'],
            'url' => '/portfolio/',
        ],
        [
            'title' => 'VidyaPilot',
            'category' => 'EdTech Platform',
            'image' => 'vidyapilot-landing.png',
            'body' => 'AI-powered Olympiad learning platform with dashboard-style positioning, course navigation and student progress flow.',
            'tech' => ['Laravel', 'AI Tutor', 'EdTech', 'Dashboard'],
            'url' => '/portfolio/',
        ],
        [
            'title' => 'Popular Holidays',
            'category' => 'Travel Website',
            'image' => 'popular-holidays.png',
            'body' => 'A holiday discovery experience with vivid destination imagery, search-first layout and mobile-friendly structure.',
            'tech' => ['WordPress', 'Booking UX', 'SEO', 'Travel'],
            'url' => '/portfolio/',
        ],
        [
            'title' => 'Little Steps',
            'category' => 'Education Website',
            'image' => 'little-steps.png',
            'body' => 'A friendly school website experience with clear navigation, parent-focused content and strong visual hierarchy.',
            'tech' => ['WordPress', 'Education', 'UI/UX', 'CMS'],
            'url' => '/portfolio/',
        ],
    ],
];
